# Generated by Django 4.2 on 2024-08-17 20:36

from django.db import migrations, models
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_auther',
            field=models.BooleanField(default=False, verbose_name='وضعیت نویسنده'),
        ),
        migrations.AddField(
            model_name='user',
            name='special_user',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='کاربرویژه تا '),
        ),
    ]
