# Generated by Django 4.2 on 2024-08-18 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("status", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
                ),
                ("thumbnail", models.ImageField(upload_to="")),
                (
                    "publish",
                    django_jalali.db.models.jDateTimeField(
                        default=django.utils.timezone.now
                    ),
                ),
                ("created", django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ("update", django_jalali.db.models.jDateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("d", "Draft"), ("p", "Published")],
                        default="d",
                        max_length=1,
                    ),
                ),
                ("reading_time_minutes", models.IntegerField()),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(related_name="articles", to="blog.category"),
                ),
            ],
            options={
                "ordering": ["-publish"],
            },
        ),
    ]
